import type { Exam } from './types';
import generated from './exams.json';
import extra from './extra-exams.json';

/**
 * exams.json is generated by `npm run build:exams` (kananinirav, MIT) and gets overwritten,
 * so hand-added sets live in extra-exams.json.
 */
export const EXAMS: Exam[] = [...(generated as Exam[]), ...(extra as Exam[])];
